[package]
name = "pw-extract"
version = "0.1.0"
authors = ["Ben Cromwell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "5.0.0"
